libs =
#import libs += libhello%lib{hello}
import libs += glm%lib{glm}
import libs += glfw%lib{glfw}
import libs += glew%lib{glew}
import libs += libimgui%lib{imgui}
import libs += libimgui-platform-glfw%lib{imgui-platform-glfw}
import libs += libimgui-render-opengl3%lib{imgui-render-opengl3}

exe{aurora-engine}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_root/lib/**/*"
